POST http://localhost:20202/api/agent/v1/register
Content-Type: application/json

{"host": "localhost", "port": 16666}

###
POST http://localhost:20202/api/agent/v1/offline
Content-Type: application/json

{"host": "localhost", "port": 16666}

###
POST http://localhost:20202/api/agent/v1/send
Content-Type: application/json

{
  "host": "172.29.96.1",
  "port": 16666,
  "command": "dir c:"
}
