POST http://localhost:10101/api/agent/v1/register
Content-Type: application/json

{"host": "localhost", "port": 16666}

###
POST http://localhost:10101/api/agent/v1/offline
Content-Type: application/json

{"host": "localhost", "port": 16666}

###
POST http://localhost:10101/api/agent/v1/send
Content-Type: application/json

{
  "host": "192.168.0.196",
  "port": 16666,
  "command": "dir d:"
}
