server:
  port: 10101
spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:point-console.db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLiteDialect
  jackson:
    time-zone: "GMT+8"
    serialization:
      write-dates-as-timestamps: false
  messages:
    basename: i18n/messages