server:
  port: 16666
spring:
  application:
    name: point-agent
  jackson:
    time-zone: "GMT+8"
    serialization:
      write-dates-as-timestamps: false
app:
  console:
    charset: GBK
point:
  console:
    server-addr: http://localhost:10101

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST,OPTION,PUT,DELETE"
      exposure:
        include: "*"
  endpoint:
    jmx:
      exposure:
        include: "health,info"
    shutdown:
      enabled: true
